# Generated by Django 3.0 on 2019-12-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='telegram_id',
            field=models.IntegerField(null=True),
        ),
    ]
