# Generated by Django 3.0 on 2019-12-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_myuser_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
    ]
