# Generated by Django 3.0 on 2019-12-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0003_auto_20191222_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='email',
            new_name='username',
        ),
    ]
